### ISSUE TITLE
missing jq command

### ISSUE THREAD

**Issue by youen** [adrienaury/go-devcontainer#3]
The  `jq` command is missing

```
> docker run -it adrienaury/go-devcontainer-ci:v0.5
/ $ jq
/bin/sh: jq: not found
/ $ 
```

this is tricky because vscode server install `jq` but not the github action. So venom tests using `jq` run successfuly in local vscode devcontainer and failed in CI.

**Comment by adrienaury** [comment]
Actually jq is installed on the "-slim" image, there is 3 images available : 
- ci : minimal image made for very light ci
- slim : ci + some tools (including jq)
- full : heavy image with all tools, use it in dev container

So I think if you need jq in the ci build, you should just replace -ci by -slim in the image name.
